### ISSUE TITLE
/bin/sh: 1: /src/init.sh: Permission denied

### ISSUE THREAD

**Issue by kiwijunglist** [sbruggeman/pwrstat-api#4]
Hi

I used to have this working but i reinstalled my OS.
I kept my docker-compose file and my original config files
However I am now getting this error:

```
/bin/sh: 1: /src/init.sh: Permission denied
```

```
  upsstatus: 
    container_name: ups_status
    restart: always
    build: 
      context: /home/mike/.config/appdata/upsstatus
      dockerfile: /home/mike/.config/appdata/upsstatus/dockerfile
    image: ups_status 
    devices:
      - /dev/bus/usb:/dev/bus/usb 
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    privileged: true 
    ports:
      - 5002:5002 
```

```
$ lsusb
...
Bus 001 Device 003: ID 0764:0501 Cyber Power System, Inc. CP1500 AVR UPS
...
```

Can you please let me know what I can do to troubleshoot this issue
